#!/bin/sh

if [ -n $R]; then
	R="/usr/local/bin/R"
else
	R="R"
fi

mkdir tmp
cp -r ernm tmp/ernm
rm -rf tmp/ernm/Debug
rm -rf tmp/ernm/.cproject
rm -rf tmp/ernm/.project
rm -rf tmp/ernm/mkdist
cp -rf tmp/ernm/src/*.h tmp/ernm/inst/include
cp -rf tmp/ernm/src/tests/* tmp/ernm/src
rm -rf tmp/ernm/src/tests
$R CMD build tmp/ernm
rm -rf tmp
$R CMD INSTALL ernm_1.0.tar.gz
