# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393


#' An basic example of a function in C++ using ernm
#' @return a list of a character vector, a numeric vector, and an ernm DirectedNet
#' @examples
#' ernm_hello_world()
#'
#' #MinDegree is an new statistic defined by this package
#' if(require(network)){
#' 	data(flo)
#' 	nflo<-as.BinaryNet(network(flo,directed=FALSE) )
#' 	fit <- ernm(nflo ~ edges() + minDegree(3),verbose=0)
#' 	summary(fit)
#' }
ernm_hello_world<- function() {}

Rcpp::loadModule("ErnmExtension_RcppExports", 
    what = c("ernm_hello_world"))
