// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP initStats();
RcppExport SEXP initToggles();
RcppExport SEXP _rcpp_module_boot_ernm();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_ernm", (DL_FUNC) &_rcpp_module_boot_ernm, 0},
    {"initStats",   (DL_FUNC) &initStats,   0},
    {"initToggles", (DL_FUNC) &initToggles, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ernm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
