// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/ernm.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// initStats
void initStats();
RcppExport SEXP _ernm_initStats() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    initStats();
    return R_NilValue;
END_RCPP
}
// initToggles
void initToggles();
RcppExport SEXP _ernm_initToggles() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    initToggles();
    return R_NilValue;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_ernm();

static const R_CallMethodDef CallEntries[] = {
    {"_ernm_initStats", (DL_FUNC) &_ernm_initStats, 0},
    {"_ernm_initToggles", (DL_FUNC) &_ernm_initToggles, 0},
    {"_rcpp_module_boot_ernm", (DL_FUNC) &_rcpp_module_boot_ernm, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ernm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
