# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.initStats <- function() {
    invisible(.Call('_ernm_initStats', PACKAGE = 'ernm'))
}

.initToggles <- function() {
    invisible(.Call('_ernm_initToggles', PACKAGE = 'ernm'))
}

